image: python:3.12

stages:
  - test
  - docs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  tags:
    - local

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

tests_and_types:
  stage: test
  script:
    - pytest
    - mypy src
  artifacts:
    when: always
    paths:
      - .mypy_cache
      - .pytest_cache
    expire_in: 1 week

pages:
  stage: docs
  script:
    - cd docs
    - make html
    - cd ..
    - rm -rf public
    - mkdir -p public
    - cp -r docs/build/html/* public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - dev
    - main
    - master
